config/routes.rb
CsnipNew::Application.routes.draw do
  devise_for :users
  resources :appointments do
    get 'search', :on => :collection
    post 'print', :on => :collection
    post 'approve', :on => :member
    post 'deny', :on => :member
  end
  
  root :to => "appointments#index"
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  validates :last_name, :first_name, :phone, :best_time_to_contact_client, :street, :city, :postal_code, :county, :presence => true
  validates :pet_name, :pet_type, :gender, :presence => true
  
  validates :weight, :presence => { :if => lambda { |appt| appt.pet_type == "dog" } }
  validates :breed, :presence => { :if => lambda { |appt| appt.pet_type == "dog" } }  
  validates :pet_testicles_descended, :presence => { :if => lambda { |appt| appt.gender == "male" } }
  validates :testicle_count, :presence => { :if => lambda { |appt| appt.gender == "male" && appt.pet_testicles_descended == "yes" } }
  validates :request_date, :presence => true, :date => { :after => Time.now, :before => Time.now + 3.weeks }
  validates :date_of_birth, :presence => true, :date => { :before => Time.now }
  validates :email, :confirmation => true
  
  before_create :set_acquired_from
  before_create :set_status_to_pending
  
  attr_accessor :acquired_from_type, :acquired_from_other_description, :requested_appointment_date
  attr_reader :age
  
  class << self
    def by_last_name(last_name)
      where("last_name LIKE ?", "%#{last_name}%")
    end
    
    def by_county(county)
      where("county LIKE ?", "%#{county}%")
    end
    
    def by_zip(postal_code)
      where(:postal_code => postal_code)
    end
    
    def by_pet_type(pet_type)
      where(:pet_type => pet_type)
    end
    
    def from_date(from)
      where("created_at >= ?", from)
    end
    
    def to_date(to)
      where(["created_at <= ?", to + 1.day])
    end
    
    def older
      where("date_of_birth <= ?", Time.now - 6.months)
    end
    
    def younger
      where("date_of_birth > ?", Time.now - 6.months)
    end
    
    def vaccinated
      where("pet_vaccinated LIKE '%Yes%'")
    end
    
    def not_vaccinated
      where("pet_vaccinated LIKE '%No %'")
    end
    
    def seen_vet
      where(:has_pet_seen_vet => true)
    end
    
    def not_seen_vet
      where(:has_pet_seen_vet => false)
    end
    
    def by_status(status)
      where(:status => status)
    end
    
    def printed
      where("printed_date IS NOT NULL")
    end
    
    def not_printed
      where("printed_date IS NULL")
    end
  end
  
  def requested_appointment_date=(val)
    begin
      self.request_date = Date.strptime(params[:appointment][:request_date], "%Y-%m-%d")
    rescue
      self.request_date = nil
    end
  end
  
  def set_acquired_from
    if acquired_from_type == 'other'
      self.acquired_from = "other: #{acquired_from_other_description}"
    elsif acquired_from_type.blank?
      self.acquired_from = "none"
    else
      self.acquired_from = acquired_from_type
    end
  end
  
  def person_attributes
      { :first_name => first_name, 
        :last_name => last_name, 
        :phone => phone, 
        :best_time_to_contact_client => best_time_to_contact_client,
        :email => email,
        :request_date => request_date,
        :street => street,
        :city => city, 
        :postal_code => postal_code, 
        :county => county, 
        :alternate_phone => alternate_phone
      }
   end
   
   def client_name_last_comma_first
       [last_name, first_name].join(', ')
     end
     
     def client_full_name
       [first_name, last_name].join(' ')
     end
  
  def age
    if self.date_of_birth.blank?
      "Unknown"
    else
      years = Time.now.to_date.year - date_of_birth.year
      months = Time.now.to_date.month - date_of_birth.month
      "#{years} year(s), #{months} month(s)"
    end
  end
  
  def birth_date
    if self.date_of_birth.blank?
      self.date_of_birth_text
    else
      self.date_of_birth.strftime("%m-%d-%Y")
    end
  end
  
  def set_status_to_pending
    self.status = "PENDING"
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create]

  def index
    if current_user.is_admin?
      @search = Appointment.order('id DESC')
      if params.has_key?(:last_name)
        @search = @search.by_last_name(params[:last_name])
      end
    
      if params.has_key?(:county)
        @search = @search.by_county(params[:county])
      end
    
      if params.has_key?(:zip)
        @search = @search.by_zip(params[:zip])
      end
    
      if params.has_key?(:pet_type)
        @search = @search.by_pet_type(params[:pet_type])
      end
    
      if params.has_key?(:age)
        @search = params[:age] == "1" ? @search.younger : @search.older
      end
    
      if params.has_key?(:from)
        from_date = Date.strptime(params[:from], "%Y-%m-%d")
        @search = @search.from_date(from_date)
      end
    
      if params.has_key?(:to)
        to_date = Date.strptime(params[:to], "%Y-%m-%d")
        @search = @search.to_date(to_date)
      end
    
      if params.has_key?(:pet_vaccinated)
        @search = params[:pet_vaccinated] == "1" ? @search.vaccinated : @search.not_vaccinated
      end
    
      if params.has_key?(:seen_vet)
        @search = params[:seen_vet] == "1" ? @search.seen_vet : @search.not_seen_vet
      end
    
      if params.has_key?(:status)
        @search = @search.by_status(params[:status])
      end
    
      if params.has_key?(:printed)
        @search = params[:printed] == "1" ? @search.printed : @search.not_printed
      end
    
      #@search.pet_type_equals_any = %w[dog cat] unless params[:search] && params[:search][:pet_type_equals_any]
      @appointments = @search.paginate(:page => params[:page], :per_page => 50)
    
      render :layout => 'admin'
    else
      redirect_to new_appointment_path
    end
  end
  
  def search
    search_params = {}
    search_params[:last_name] = Regexp.escape(params[:last_name]) if params.has_key?(:last_name) && !params[:last_name].blank?
    search_params[:county] = Regexp.escape(params[:county]) if params.has_key?(:county) && !params[:county].blank?
    search_params[:zip] = Regexp.escape(params[:zip]) if params.has_key?(:zip) && !params[:zip].blank?
    search_params[:pet_type] = Regexp.escape(params[:pet_type]) if params.has_key?(:pet_type) && !params[:pet_type].blank?
    search_params[:age] = Regexp.escape(params[:age]) if params.has_key?(:age) && !params[:age].blank?
    search_params[:pet_vaccinated] = Regexp.escape(params[:pet_vaccinated]) if params.has_key?(:pet_vaccinated) && !params[:pet_vaccinated].blank?
    search_params[:from] = params[:from] if params.has_key?(:from) && !params[:from].blank?
    search_params[:to] = params[:to] if params.has_key?(:to) && !params[:to].blank?
    search_params[:seen_vet] = Regexp.escape(params[:seen_vet]) if params.has_key?(:seen_vet) && !params[:seen_vet].blank?
    search_params[:status] = params[:status] if params.has_key?(:status) && !params[:status].blank?
    search_params[:printed] = params[:printed] if params.has_key?(:printed) && !params[:printed].blank?
    respond_to do |format|
      format.html { redirect_to(appointments_path(search_params)) }
      format.js
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
    render :layout => 'admin'
  end

  def print
    @appointments = Appointment.find(params[:ids])
    @appointments.each do |appt|
      appt.update_attributes(:printed_date => Time.now)
    end
    render :layout => 'print'
  end

  def new
    @appointment = Appointment.new(params[:appointment])
  end

  def create
    @appointment = Appointment.new(params[:appointment])
    if @appointment.save
      AppointmentMailer.appointment_submitted(@appointment).deliver unless @appointment.email.blank? 
      render :layout => 'application'
    else
      render :action => :new, :layout => 'application'
    end
  end
  
  def approve
    @appointment = Appointment.find(params[:id])
    if @appointment.update_attributes(:status => "APPROVED")
      flash[:notice] = "Appointment #{@appointment.id.to_s} with #{@appointment.client_full_name} has been approved."
      AppointmentMailer.appointment_accepted(@appointment).deliver unless @appointment.email.blank?
      redirect_to appointments_path
    else
      render :action => 'show'
    end
  end
  
  def deny
    @appointment = Appointment.find(params[:id])
    if @appointment.update_attributes(:status => "DENIED")
      flash[:warn] = "Appointment #{@appointment.id.to_s} with #{@appointment.client_full_name} has been denied."
      AppointmentMailer.appointment_denied(@appointment).deliver unless @appointment.email.blank?
      redirect_to appointments_path
    else
      render :action => 'show'
    end
  end

end

app/views/appointments/_appointment.html.erb
<h2 class="left"><%= appointment.client_name_last_comma_first %></h2>
<h2 class="right">Apt #<%= appointment.id %></h2>
<div class="clear"></div>
<div class="right">
	<p class="right">Created on: <%= appointment.created_at.to_formatted_s(:standard) %></p><br />
	<p class="right">Requested for: <%= appointment.request_date.strftime("%A, %B %d, %Y") unless appointment.request_date.blank? %></p>
</div>
<div class="left">
	<div class="contact-info left">
		<p><%= appointment.street %></p>
		<p><%= appointment.city %></p>
		<p><%= appointment.postal_code %></p>
		<p><%= appointment.county %></p>
		<p><%= mail_to(h(appointment.email)) unless appointment.email.blank? %></p>
		<p><%= formatted_phone(appointment.phone) %></p>
		<p><%= formatted_phone(appointment.alternate_phone) %></p>
	</div>
</div>
<div class="clear"></div>
<div class="pet-information">
	<h3>Pet Information</h3>
	<div class="left">
		<p><strong><%= appointment.pet_name %></strong> (<%= appointment.pet_type.capitalize %> / <%= appointment.breed %>)</p>
		<p><%= appointment.gender.humanize %>, Age: <%= appointment.age %> (DOB: <%= appointment.date_of_birth %>)</p>
		<% if appointment.weight.present? %>
			<p><%= appointment.weight %></p>
		<% end %>
		<p>Color: <%= appointment.color %></p>
	</div>
	<div class="right">
		<p><strong>Chip implant?</strong>
			<% if appointment.want_chip_implant? %>
				Yes
			<% else %>
				No
			<% end %>
		</p>
	</div>
	<div class="clear"></div>
</div>
<table class="appointment" cellpadding="1" width="100%">
  <tbody>
    <tr>
      <th>What is the best time to contact you?</th>
      <td><%= appointment.best_time_to_contact_client %></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
    </tr>
    <tr>
      <th>Would you like a rabies vaccination?</th>
      <td><%= formatted_boolean(appointment.want_rabies_vaccination?) %></td>
    </tr>
    <tr>
      <th>Additional information</th>
      <td><%= appointment.comments %></td>
    </tr>
	<tr>
		<th>Acquired from?</th>
		<td><%= appointment.acquired_from %></td>
	</tr>
	<% if !(appointment.acquired_from_other_description.blank?)%>
		<tr>
			<th>Acquired from other description</th>
			<td><%= appointment.acquired_from_other_description %>
		</tr>
	<% end %>
	<tr>
		<th>Owned for how long?</th>
		<td><%= appointment.owned_for %>
	</tr>
	<tr>
		<th>Where does your pet live?</th>
		<td><%= appointment.where_pet_lives %></td>
	</tr>
	<tr>
		<th>Is pet tame?</th>
		<td><%= appointment.is_pet_tame == true ? "NO" : "yes" %></td>
	</tr>
    <tr>
      <th>Is your pet in heat?</th>
      <td><%= appointment.pet_in_heat %></td>
    </tr>
    <tr>
      <th>Is your pet pregnant?</th>
      <td><%= appointment.pet_pregnant %></td>
    </tr>
	<tr>
		<th>Has your pet had a litter?</th>
		<td><%= appointment.has_had_litter %></td>
	</tr>
    <tr>
      <th>When did your pet last have a litter?</th>
      <td><%= appointment.had_litter_when %></td>
    </tr>
    <tr>
      <th>Has your male pet's testicles descended?</th>
      <td><%= appointment.pet_testicles_descended %></td>
    </tr>
    <tr>
      <th>If so, how many?</th>
      <td><%= appointment.testicle_count %></td>
    </tr>
    <tr>
      <th>Has your pet been vaccinated?</th>
      <td><%= appointment.pet_vaccinated.humanize %></td>
    </tr>
	<tr>
		<th>Has your pet seen a vet?</th>
		<td><%= appointment.has_pet_seen_vet == 1 ? "no" : "yes" %></td>
	</tr>
    <tr>
      <th>Veterinarian's name</th>
      <td><%= appointment.vet_name %></td>
    </tr>
    <tr>
      <th>Any previous surgery? If so, please explain</th>
      <td><%= appointment.surgeries_explanation %></td>
    </tr>
    <tr>
      <th>Any previous health issues? If so, please explain</th>
      <td><%= appointment.health_concerns_explanation %></td>
    </tr>
    <tr>
      <th>Any medications? If so, please explain</th>
      <td><%= appointment.medications_explanation %></td>
    </tr>
  </tbody>
</table>

app/views/appointments/create.html.erb
<div class="thanks">
	<p>Thank you for providing information about you and your pet. Doing so online allows us to devote more of our resources to taking care of your pet.</p>
	<p>We will call you within 3 to 5 business days for any further information and to schedule an appointment.</p>
	<%= link_to "Click here if you have another pet to add", new_appointment_path(:appointment => @appointment.person_attributes) %>
	<p>&nbsp;</p>
</div>

app/views/appointments/index.html.erb
<div id="appointments_listing">
  <h2>Appointments</h2>
  <div class="search">
	   <%= form_tag search_appointments_path, :method => :get %>
		    <%= label_tag :last_name %>
		    <%= text_field_tag :last_name, params[:last_name], :size => 15 %>

		    <%= label_tag :county %>
		    <%= text_field_tag :county, params[:county], :size => 15 %>

		    <%= label_tag "Zipcode" %>
		    <%= text_field_tag :zip, params[:zip], :size => 10 %>

		    <span class="separator">|</span>
				<%= label_tag "Pet Type" %>
				<%= select_tag :pet_type, options_for_select(['', 'Cat', 'Dog']) %>
		    <span class="separator">|</span>

		    <label>Dates</label>
		    <%= text_field_tag :from, params[:from], :size => 11, :class => "date_picker" %>

		    <span>-</span>
		    <%= text_field_tag :to, params[:to], :size => 11, :class => "date_picker" %>
				<br />
		
				<%= label_tag "Age" %>
				<%= select_tag :age, options_for_select([['', nil], ['6 months & under', 1], ['Over 6 months', 2]]) %>
				
				<span class="separator">|</span>
				<%= label_tag "Pet Vaccinated?" %>
				<%= select_tag :pet_vaccinated, options_for_select([['', ''], ['Yes', 1], ['No', 0]]) %>
			
				<span class="separator">|</span>
				<%= label_tag "Seen a vet?" %>
				<%= select_tag :seen_vet, options_for_select([['', ''], ['Yes', 1], ['No', 0]]) %>
				
				<span class="separator">|</span>
				<%= label_tag "Status" %>
				<%= select_tag :status, options_for_select(['', 'PENDING', 'APPROVED', 'DENIED']) %>
				
				<span class="separator">|</span>
				<%= label_tag "Printed?" %>
				<%= select_tag :printed, options_for_select([['', ''], ['Yes', 1], ['No', 0]]) %>

		    <%= submit_tag "Search" %>
		  </form>
	  </div>
  <div class="search_statistics">
    Search returned <strong><%= number_with_delimiter(@search.count) %></strong> results: 
    <strong><%= @search.count(:conditions => {:pet_type => 'cat'}) %></strong> cats and 
    <strong><%= @search.count(:conditions => {:pet_type => 'dog'}) %></strong> dogs.
  </div>
  <% if @appointments.blank? %>
    <h3 class="no_data">There are no appointments matching the criteria you've selected.</h3>
  <% else %>
    <%= will_paginate @appointments %>
    <%= form_tag print_appointments_path %>
	  <fieldset>
	 <%= submit_tag "Print Selected" %>	
      <table>
        <thead>
          <tr>
            <th><input id="check_all" type="checkbox" class="checkall"></th>
            <th> ID </th>
            <th> Client Name </th>
            <th> Phone </th>
            <th> Pet Name </th>
            <th> Pet Type </th>
            <th> Pet Sex </th>
            <th> Vaccinated? </th>
            <th> Pregnant? </th>
			<th> Status </th>
            <th> &nbsp; </th>
          </thead>
        <tbody>
          <% @appointments.each do |appointment| %>
            <tr id="appointment_<% appointment.id %>">
              <td>
                <%= check_box_tag "ids[]", appointment.id, false, :id => "appointment_checkbox_#{appointment.id}", :class => "appointment_check_box" %>
              </td>
              <td>
                <%= appointment.id %>
              </td>
              <td>
                <%= appointment.client_name_last_comma_first %>
              </td>
              <td>
                <%= formatted_phone(appointment.phone) %>
                <br />
                <%= formatted_phone(appointment.alternate_phone) %>
              </td>
              <td>
                <%= appointment.pet_name %>
              </td>
              <td>
                <%= appointment.pet_type.capitalize %>
              </td>
              <td>
                <%= appointment.gender.humanize %>
              </td>
              <td>
                <%= appointment.pet_vaccinated.to_s.humanize %>
              </td>
              <td>
                <%= appointment.pet_pregnant.to_s.humanize %>
              </td>
			  <td>
			    <%= appointment.status.upcase unless appointment.status.blank? %>
			   </td>
              <td>
                <%= link_to 'Show', appointment %>
              </td>
            </tr>
          <% end %>
          <tr class="last">
            <td colspan="2">
              <%= submit_tag "Print Selected", :id => "print_submit" %>
            </td>
            <td colspan="8">&nbsp;</td>
          </tr>
        </tbody>
      </table>
     </fieldset>
    </form>
    <%- end -%>
    <%= will_paginate @appointments %>
  </div>
</div>
<script type="text/javascript">
  $(function() {
    $(".date_picker").datepicker({ dateFormat: 'yy-mm-dd'});
  });
	$(function () {
		$('.checkall').click(function () {
			$(this).parents('fieldset:eq(0)').find(':checkbox').attr('checked', this.checked);
		});
	});
</script>

app/views/appointments/new.html.haml
<div class="request">
	<h1>Request an Appointment for your Pet</h1>
	<div class="errorExplanationContainer">
		<%= error_messages_for :appointment, :class => "error" %>
	</div>
	<%- form_for @appointment, :html => { :class => "bp" } do |f| -%>
		<div class="user_info">
			<fieldset>
				<legend>Contact Information</legend>
				<p class="required">
					<%= f.label :first_name %><br />
					<%= f.text_field :first_name %>
				</p>
				<p class="required">
				  <%= f.label :last_name %><br />
				  <%= f.text_field :last_name %>
				</p>
				<p class="required">
				  <%= f.label :phone %><br />
				  <%= f.text_field :phone %><br />
					<span class="notes">e.g., (616) 555-5555</span>
				</p>
				<p class="required">
				  <%= f.label :best_time_to_contact_client, "What is the best time to contact you?" %><br />
				  <%= f.text_field :best_time_to_contact_client %>
				</p>
				<p class="required">
				  <%= f.label :alternate_phone %><br />
				  <%= f.text_field :alternate_phone %><br />
					<span class="notes">e.g., (616) 555-5555</span>
				</p>
				<p class="required">
				  <%= f.label :email %><br />
				  <%= f.text_field :email %>
				</p>
			</fieldset>
		</div>
		<div class="address_container">
			<fieldset>
				<legend>Address</legend>
				<p class="required">
				  <%= f.label :street, "Street Address" %><br />
				  <%= f.text_field :street %>
				</p>
				<p class="required">
				  <%= f.label :city %><br />
				  <%= f.text_field :city %>
				</p>
				<p class="required">
				  <%= f.label :postal_code, "Zipcode" %><br />
				  <%= f.text_field :postal_code %>
				</p>
				<p class="required">
				  <%= f.label :county %><br />
				  <%= f.text_field :county %>
				</p>
			</fieldset>
		</div>
		<div class="pet_information clear">
			<fieldset>
				<legend>Basic Pet Information</legend>
				<p class="required">
				  <%= f.label :pet_name %><br />
				  <%= f.text_field :pet_name %>
				</p>
				<p class="required">
				  <%= label_tag "Your pet is a" %><br />
				  <%= f.radio_button :pet_type, :dog %>
					<%= f.label :pet_type, "Dog", :value => :dog %><br />
					<%= f.radio_button :pet_type, :cat %>
					<%= f.label :pet_type, "Cat", :value => :cat %>
				</p>
				<p class="required">
				  <%= f.label :gender %><br />
				  <%= f.text_field :gender %>
				</p>
				<p class="required">
				  <%= f.label :age %><br />
				  <%= f.text_field :age %><br />
					<span class="notes">e.g., 8 years, about 2 months</span>
				</p>
				<p class="dog_only">
				  <%= f.label :weight %><br />
				  <%= f.text_field :weight %><br />
					<span class="notes">An approximate is fine</span>
				</p>
				<p class="required">
				  <%= f.label :date_of_birth %><br />
				  <%= f.text_field :date_of_birth %>
				</p>
				<p class="dog_only">
				  <%= f.label :breed %><br />
				  <%= f.text_field :breed %>
				</p>
				<p class="required">
				  <%= f.label :color %><br />
				  <%= f.text_field :color %>
				</p>
				<p class="required">
				  <%= f.check_box :want_chip_implant %><br />
					<%= f.label :want_chip_implant, "Would you like a chip implant?" %>
				</p>
				<p class="required">
				  <%= f.text_field :want_rabies_vaccination %><br />
					<%= f.label :want_rabies_vaccination, "Would you like a rabies vaccination?" %>
				</p>
				<p class="required">
				  <%= f.label :comments, "Please list any other information you have:" %><br />
				  <%= f.text_area :comments %>
				</p>
			</fieldset>
		</div>
		<div class="pet_history">
			<fieldset>
				<legend>Pet History</legend>
				<p class="required">
				  <%= f.label :acquired_from_type %><br />
				  <%= f.radio_button :acquired_from_type, :stray %>
					<%= f.radio_button :acquired_from_type, :adopted %>
					<%= f.radio_button :acquired_from_type, :friend %>
					<%= f.radio_button :acquired_from_type, :breeder %>
					<%= f.radio_button :acquired_from_type, :other %>
					<span style="margin-left: 20px">
						<%= f.text_field :acquired_from_other_description %>
					</span>
				</p>
				<p class="required">
				  <%= f.label :owned_for, "How long have you owned your pet?" %><br />
				  <%= f.text_field :owned_for %><br />
					<span class="notes">e.g., 1 year, about 18 months</span>
				</p>
				<p class="required">
				  <%= f.label :pet_vaccinated, "Has your pet been vaccinated?" %><br />
				  <%= f.radio_button :pet_vaccinated, :yes %>
					<%= f.radio_button :pet_vaccinated, :no %>
					<%= f.radio_button :pet_vaccinated, :not_sure %>
				</p>
				<p class="required">
				  <%= f.label :vet_name, "Veterinarian's Name" %><br />
				  <%= f.text_field :vet_name %>
				</p>
				<p class="required">
				  <%= f.label :surgeries_explanation, "Any previous surgery? If so, please explain:" %><br />
				  <%= f.text_area :surgeries_explanation %>
				</p>
				<p class="required">
				  <%= f.label :health_concerns_explanation, "Any health issues? If so, please explain:" %><br />
				  <%= f.text_area :health_concerns_explanation %>
				</p>
				<p class="required">
				  <%= f.label :medications_explanation, "Any medications? If so, please explain:" %><br />
				  <%= f.text_field :medications_explanation %>
				</p>
				<p class="required">
				  <%= f.label :pet_in_heat, "Is your pet in heat?" %><br />
				  <%= f.radio_button :pet_in_heat, :yes %>
					<%= f.radio_button :pet_in_heat, :no %>
					<%= f.radio_button :pet_in_heat, :not_sure %>
				</p>
				<p class="required">
				  <%= f.label :pet_pregnant, "Is your pet pregnant?" %><br />
				  <%= f.radio_button :pet_pregnant, :yes %>
					<%= f.radio_button :pet_pregnant, :no %>
					<%= f.radio_button :pet_pregnant, :not_sure %>
				</p>
				<p class="required">
				  <%= f.label :had_litter_when, "Has your pet had a litter? If so, when?" %><br />
				  <%= f.text_field :had_litter_when %>
				</p>
				<p class="required">
				  <%= f.label :pet_testicles_decended, "Has your male pet's testicles decended?" %><br />
				  <%= f.radio_button :pet_testicles_decended, :yes %>
					<%= f.radio_button :pet_testicles_decended, :no %>
					<%= f.radio_button :pet_testicles_decended, :not_sure %>
				</p>
				<p class="required">
				  <%= f.label :testicle_count, "If so, how many?" %><br />
				  <%= f.radio_button :testicle_count, 1 %>
					<%= f.radio_button :testicle_count, 2 %>
				</p>
			</fieldset>
		</div>
		<div class="finished">
			<fieldset>
				<%= f.submit "I'm Done, send the request to C-SNIP" %>
			</fieldset>
		</div>
	<%- end -%>
</div>

app/views/appointments/print.html.erb
<div id="admin_nav" style="padding-left: 10px;">
  <%= link_to '<< Back to Appointment Listing', appointments_url %>
</div>
<%= render :partial => 'appointment', :collection => @appointments %>

app/views/appointments/show.html.erb
<div></div>
<div class="errorExplanationContainer">
  <% if @appointment.errors.any? %>
    <h2><%= pluralize(@appointment.errors.count, "error") %> encountered while saving:</h2>
    <ul>
	  <% @appointment.errors.full_messages.each do |msg| %>
	    <li class="error"><%= msg %></li>
	  <% end %>
    </ul>
  <% end %>
</div>
<%= render @appointment %>
<div class="appointment_buttons">
	<%- unless @appointment.status.blank? -%>
	<%- if @appointment.status.upcase == "PENDING" -%>
		<%= form_tag approve_appointment_path(@appointment) %>
			<%= submit_tag 'Approve' %>
		</form>
		<%= form_tag deny_appointment_path(@appointment) %>
			<%= submit_tag 'Deny' %>
		</form>
	<%- end -%>
	<%- end -%>
</div>